name: make kernel op9r meteoric new

on:
  workflow_dispatch:

    inputs:
      KERNEL_SOURCE:
        description: 'Kernel Source'
        required: true
        default: 'https://github.com/Project-Zephyrus/meteoric_kernel'
        
      KERNEL_SOURCE_BRANCH:
        description: 'Branch'
        required: true
        default: 'meteoric-OOS'
        
      KERNEL_DEFCONFIG:
        description: 'Defconfig'
        required: true
        default: 'meteoric_defconfig'

      CLANG_URL:
        description: 'Clang URL'
        required: true
        default: 'https://github.com/ZyCromerZ/Clang/releases/download/14.0.6-20240212-release/Clang-14.0.6-20240212.tar.gz'
        # default: 'https://github.com/ZyCromerZ/Clang/releases/download/17.0.0-20230725-release/Clang-17.0.0-20230725.tar.gz'

      shell:
        description: 'shell'
        required: false
        default: 'git submodule init ; git submodule update'      
      
      zip_name:
        description: 'zip name'
        required: true
        default: 'meteoric-OOS11' 
      
      ksu_path_or_KPROBES:
        description: '[0，1，2，3,  4]->[path-su,kprobes-su,only-path-su,only-kprobes-su,no-su]'
        required: true
        default: '2' 
      
      ksu_version:
        description: '[v0.9.5, main, v0.9.3 .etc]->[非gki设备仅支持到v0.9.5]'
        required: true
        default: 'v0.9.5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: 配置环境
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "DEVICE=$(echo ${{ github.event.inputs.KERNEL_DEFCONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3

    - name: 下载clang和内核源
      run: |
        mkdir clang
        aria2c -j10 ${{ github.event.inputs.CLANG_URL }} -o clang.tar.gz
        tar -C clang/ -zxf clang.tar.gz
        git clone --depth=1 ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }} android-kernel
        cd android-kernel
        ${{ github.event.inputs.shell }}
       
    - name: 编译内核
      run: |
        cd android-kernel
        export CLANG_PATH=$GITHUB_WORKSPACE/clang
        export PATH=${CLANG_PATH}/bin:${PATH}
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_COMPILER_STRING="$(clang --version | head -n 1 )"
        export KBUILD_BUILD_HOST=axin-linux
        export KBUILD_BUILD_USER=axin  
        
        cat > AnyKernel3.sh <<end
        rm -rf AnyKernel3
        git clone --depth=1 https://github.com/r8ter/AnyKernel3 AnyKernel3
        rm -rf AnyKernel3/.git
        mv out/arch/arm64/boot/dtbo.img AnyKernel3/ || echo "没有dtbo.img"
        mv out/arch/arm64/boot/Image AnyKernel3/
        mv kernel.log AnyKernel3/
        cd AnyKernel3
        zip -r \$1-\$2-$(TZ=Asia/Shanghai date "+%Y%m%d%H%M").zip *
        mkdir ../../666 || echo ""
        cp -r \$1-\$2-$(TZ=Asia/Shanghai date "+%Y%m%d%H%M").zip ../../666
        end
        
        if [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "0" ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "1" ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "4" ];then
        make O=out -j$(nproc --all) CC="ccache clang" CXX="ccache clang++" ARCH=arm64 CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld ${{ github.event.inputs.KERNEL_DEFCONFIG }}
        echo "----------------------------"
        sed s/CONFIG_LOCALVERSION=".*"/'CONFIG_LOCALVERSION="-perf-ksu-axin"'/g out/.config >>.config1
        rm -rf out/.config
        mv .config1 out/.config
        make O=out -j$(nproc --all) CC="ccache clang" CXX="ccache clang++" ARCH=arm64 CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld || exit 2>&1 | tee kernel.log
        sh AnyKernel3.sh ${{ github.event.inputs.zip_name }}
        fi

        if [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "0" ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "1" ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "2" ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} == "3" ];then
        echo -e "\n\n\n\n"
        echo "--------------加入ksu编译-----------------"
        rm -rf KernelSU
        make O=out CC="ccache clang" CXX="ccache clang++" ARCH=arm64 CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld ${{ github.event.inputs.KERNEL_DEFCONFIG }}
        echo "----------------------------"
        sed s/CONFIG_LOCALVERSION=".*"/'CONFIG_LOCALVERSION="-perf-ksu-axin"'/g out/.config >>.config1
        rm -rf out/.config
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ github.event.inputs.ksu_version }}

        hh="
        CONFIG_KERNELSU=y
        CONFIG_KPROBES=y
        CONFIG_HAVE_KPROBES=y
        CONFIG_KPROBE_EVENTS=y
        CONFIG_MODULES=y
        CONFIG_MODULE_FORCE_LOAD=y
        CONFIG_SECURITY_SELINUX_DEVELOP=y
        CONFIG_DM_VERITY=y
        CONFIG_DM_VERITY_AVB=y
        "
        if [ ${{ github.event.inputs.ksu_path_or_KPROBES }} = '0' ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} = '2' ];then bash ../patches.sh ; echo "path----------" ; fi 
        if [ ${{ github.event.inputs.ksu_path_or_KPROBES }} = '1' ] || [ ${{ github.event.inputs.ksu_path_or_KPROBES }} = '3' ];then for i in $hh; do echo $i >> .config1; done; echo "kprobes----------" ; fi 
        mv .config1 out/.config
        echo "----------------------------"
        cat out/.config | grep KPROBES
        cat out/.config | grep CONFIG_MODULES
        echo "----------------------------"
        make O=out -j$(nproc --all) CC="ccache clang" CXX="ccache clang++" ARCH=arm64 CROSS_COMPILE=$CLANG_PATH/bin/aarch64-linux-gnu- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/arm-linux-gnueabi- LD=ld.lld 2>&1 | tee kernel.log               
        echo "----------------------"
        sh AnyKernel3.sh  ${{ github.event.inputs.zip_name }} "ksu"
        fi
        ls -alhF out/arch/arm64/boot/
        ls -alhF ../666/
        ls -alhF ./

